// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: notebook/v2/notebook.proto

package v2

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Principal_Type int32

const (
	Principal_USER Principal_Type = 0
)

// Enum value maps for Principal_Type.
var (
	Principal_Type_name = map[int32]string{
		0: "USER",
	}
	Principal_Type_value = map[string]int32{
		"USER": 0,
	}
)

func (x Principal_Type) Enum() *Principal_Type {
	p := new(Principal_Type)
	*p = x
	return p
}

func (x Principal_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Principal_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_notebook_v2_notebook_proto_enumTypes[0].Descriptor()
}

func (Principal_Type) Type() protoreflect.EnumType {
	return &file_notebook_v2_notebook_proto_enumTypes[0]
}

func (x Principal_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Principal_Type.Descriptor instead.
func (Principal_Type) EnumDescriptor() ([]byte, []int) {
	return file_notebook_v2_notebook_proto_rawDescGZIP(), []int{0, 0}
}

type Principal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Principal_Type `protobuf:"varint,1,opt,name=type,proto3,enum=messages.notebook.v2.Principal_Type" json:"type,omitempty"`
	Id   string         `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Principal) Reset() {
	*x = Principal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notebook_v2_notebook_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_notebook_v2_notebook_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_notebook_v2_notebook_proto_rawDescGZIP(), []int{0}
}

func (x *Principal) GetType() Principal_Type {
	if x != nil {
		return x.Type
	}
	return Principal_USER
}

func (x *Principal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadEntryGRPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Principal *Principal                    `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Payload   *ReadEntryGRPCRequest_Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ReadEntryGRPCRequest) Reset() {
	*x = ReadEntryGRPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notebook_v2_notebook_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadEntryGRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEntryGRPCRequest) ProtoMessage() {}

func (x *ReadEntryGRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notebook_v2_notebook_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEntryGRPCRequest.ProtoReflect.Descriptor instead.
func (*ReadEntryGRPCRequest) Descriptor() ([]byte, []int) {
	return file_notebook_v2_notebook_proto_rawDescGZIP(), []int{1}
}

func (x *ReadEntryGRPCRequest) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *ReadEntryGRPCRequest) GetPayload() *ReadEntryGRPCRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReadEntryGRPCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *ReadEntryGRPCResponse_Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *ReadEntryGRPCResponse) Reset() {
	*x = ReadEntryGRPCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notebook_v2_notebook_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadEntryGRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEntryGRPCResponse) ProtoMessage() {}

func (x *ReadEntryGRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notebook_v2_notebook_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEntryGRPCResponse.ProtoReflect.Descriptor instead.
func (*ReadEntryGRPCResponse) Descriptor() ([]byte, []int) {
	return file_notebook_v2_notebook_proto_rawDescGZIP(), []int{2}
}

func (x *ReadEntryGRPCResponse) GetPayload() *ReadEntryGRPCResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StartNewEntryGRPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Principal *Principal                        `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
	Payload   *StartNewEntryGRPCRequest_Payload `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *StartNewEntryGRPCRequest) Reset() {
	*x = StartNewEntryGRPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notebook_v2_notebook_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartNewEntryGRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNewEntryGRPCRequest) ProtoMessage() {}

func (x *StartNewEntryGRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notebook_v2_notebook_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNewEntryGRPCRequest.ProtoReflect.Descriptor instead.
func (*StartNewEntryGRPCRequest) Descriptor() ([]byte, []int) {
	return file_notebook_v2_notebook_proto_rawDescGZIP(), []int{3}
}

func (x *StartNewEntryGRPCRequest) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *StartNewEntryGRPCRequest) GetPayload() *StartNewEntryGRPCRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StartNewEntryGRPCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload *StartNewEntryGRPCResponse_Payload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *StartNewEntryGRPCResponse) Reset() {
	*x = StartNewEntryGRPCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notebook_v2_notebook_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartNewEntryGRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNewEntryGRPCResponse) ProtoMessage() {}

func (x *StartNewEntryGRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notebook_v2_notebook_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNewEntryGRPCResponse.ProtoReflect.Descriptor instead.
func (*StartNewEntryGRPCResponse) Descriptor() ([]byte, []int) {
	return file_notebook_v2_notebook_proto_rawDescGZIP(), []int{4}
}

func (x *StartNewEntryGRPCResponse) GetPayload() *StartNewEntryGRPCResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ReadEntryGRPCRequest_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadEntryGRPCRequest_Payload) Reset() {
	*x = ReadEntryGRPCRequest_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notebook_v2_notebook_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadEntryGRPCRequest_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEntryGRPCRequest_Payload) ProtoMessage() {}

func (x *ReadEntryGRPCRequest_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_notebook_v2_notebook_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEntryGRPCRequest_Payload.ProtoReflect.Descriptor instead.
func (*ReadEntryGRPCRequest_Payload) Descriptor() ([]byte, []int) {
	return file_notebook_v2_notebook_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ReadEntryGRPCRequest_Payload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadEntryGRPCResponse_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text      string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	CreatorId string                 `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *ReadEntryGRPCResponse_Payload) Reset() {
	*x = ReadEntryGRPCResponse_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notebook_v2_notebook_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadEntryGRPCResponse_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadEntryGRPCResponse_Payload) ProtoMessage() {}

func (x *ReadEntryGRPCResponse_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_notebook_v2_notebook_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadEntryGRPCResponse_Payload.ProtoReflect.Descriptor instead.
func (*ReadEntryGRPCResponse_Payload) Descriptor() ([]byte, []int) {
	return file_notebook_v2_notebook_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ReadEntryGRPCResponse_Payload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadEntryGRPCResponse_Payload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReadEntryGRPCResponse_Payload) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *ReadEntryGRPCResponse_Payload) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReadEntryGRPCResponse_Payload) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type StartNewEntryGRPCRequest_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatorId string `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
}

func (x *StartNewEntryGRPCRequest_Payload) Reset() {
	*x = StartNewEntryGRPCRequest_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notebook_v2_notebook_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartNewEntryGRPCRequest_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNewEntryGRPCRequest_Payload) ProtoMessage() {}

func (x *StartNewEntryGRPCRequest_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_notebook_v2_notebook_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNewEntryGRPCRequest_Payload.ProtoReflect.Descriptor instead.
func (*StartNewEntryGRPCRequest_Payload) Descriptor() ([]byte, []int) {
	return file_notebook_v2_notebook_proto_rawDescGZIP(), []int{3, 0}
}

func (x *StartNewEntryGRPCRequest_Payload) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

type StartNewEntryGRPCResponse_Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StartNewEntryGRPCResponse_Payload) Reset() {
	*x = StartNewEntryGRPCResponse_Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_notebook_v2_notebook_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartNewEntryGRPCResponse_Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNewEntryGRPCResponse_Payload) ProtoMessage() {}

func (x *StartNewEntryGRPCResponse_Payload) ProtoReflect() protoreflect.Message {
	mi := &file_notebook_v2_notebook_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNewEntryGRPCResponse_Payload.ProtoReflect.Descriptor instead.
func (*StartNewEntryGRPCResponse_Payload) Descriptor() ([]byte, []int) {
	return file_notebook_v2_notebook_proto_rawDescGZIP(), []int{4, 0}
}

func (x *StartNewEntryGRPCResponse_Payload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_notebook_v2_notebook_proto protoreflect.FileDescriptor

var file_notebook_v2_notebook_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x76, 0x32, 0x2f, 0x6e, 0x6f,
	0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e,
	0x76, 0x32, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x67, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x12, 0x38,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b,
	0x2e, 0x76, 0x32, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x10, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x00, 0x22, 0xbe, 0x01, 0x0a, 0x14, 0x52,
	0x65, 0x61, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x72,
	0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70,
	0x61, 0x6c, 0x12, 0x4c, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x6e,
	0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x1a, 0x19, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xab, 0x02, 0x0a, 0x15,
	0x52, 0x65, 0x61, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x1a, 0xc2, 0x01, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xd5, 0x01, 0x0a, 0x18, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4e, 0x65, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69,
	0x70, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x32,
	0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6e,
	0x63, 0x69, 0x70, 0x61, 0x6c, 0x12, 0x50, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x4e, 0x65, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x28, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x22, 0x89, 0x01, 0x0a, 0x19, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x65, 0x77, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x51, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x37, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x65,
	0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x65, 0x77,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x1a, 0x19, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x86, 0x02,
	0x0a, 0x08, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x74, 0x0a, 0x09, 0x52, 0x65,
	0x61, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x2a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x6e,
	0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x0e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x08, 0x12, 0x06, 0x2f, 0x65, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x83, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x65, 0x77, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x2e, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x6e, 0x6f,
	0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e,
	0x65, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x6e, 0x6f,
	0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e,
	0x65, 0x77, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x22, 0x06, 0x2f, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x3a, 0x01, 0x2a, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x61, 0x73, 0x6f, 0x6e, 0x62, 0x6c, 0x61, 0x6e, 0x63, 0x68,
	0x61, 0x72, 0x64, 0x2f, 0x64, 0x69, 0x2d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f,
	0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2f, 0x6e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x2f, 0x76, 0x32,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_notebook_v2_notebook_proto_rawDescOnce sync.Once
	file_notebook_v2_notebook_proto_rawDescData = file_notebook_v2_notebook_proto_rawDesc
)

func file_notebook_v2_notebook_proto_rawDescGZIP() []byte {
	file_notebook_v2_notebook_proto_rawDescOnce.Do(func() {
		file_notebook_v2_notebook_proto_rawDescData = protoimpl.X.CompressGZIP(file_notebook_v2_notebook_proto_rawDescData)
	})
	return file_notebook_v2_notebook_proto_rawDescData
}

var file_notebook_v2_notebook_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notebook_v2_notebook_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_notebook_v2_notebook_proto_goTypes = []interface{}{
	(Principal_Type)(0),                       // 0: messages.notebook.v2.Principal.Type
	(*Principal)(nil),                         // 1: messages.notebook.v2.Principal
	(*ReadEntryGRPCRequest)(nil),              // 2: messages.notebook.v2.ReadEntryGRPCRequest
	(*ReadEntryGRPCResponse)(nil),             // 3: messages.notebook.v2.ReadEntryGRPCResponse
	(*StartNewEntryGRPCRequest)(nil),          // 4: messages.notebook.v2.StartNewEntryGRPCRequest
	(*StartNewEntryGRPCResponse)(nil),         // 5: messages.notebook.v2.StartNewEntryGRPCResponse
	(*ReadEntryGRPCRequest_Payload)(nil),      // 6: messages.notebook.v2.ReadEntryGRPCRequest.Payload
	(*ReadEntryGRPCResponse_Payload)(nil),     // 7: messages.notebook.v2.ReadEntryGRPCResponse.Payload
	(*StartNewEntryGRPCRequest_Payload)(nil),  // 8: messages.notebook.v2.StartNewEntryGRPCRequest.Payload
	(*StartNewEntryGRPCResponse_Payload)(nil), // 9: messages.notebook.v2.StartNewEntryGRPCResponse.Payload
	(*timestamppb.Timestamp)(nil),             // 10: google.protobuf.Timestamp
}
var file_notebook_v2_notebook_proto_depIdxs = []int32{
	0,  // 0: messages.notebook.v2.Principal.type:type_name -> messages.notebook.v2.Principal.Type
	1,  // 1: messages.notebook.v2.ReadEntryGRPCRequest.principal:type_name -> messages.notebook.v2.Principal
	6,  // 2: messages.notebook.v2.ReadEntryGRPCRequest.payload:type_name -> messages.notebook.v2.ReadEntryGRPCRequest.Payload
	7,  // 3: messages.notebook.v2.ReadEntryGRPCResponse.payload:type_name -> messages.notebook.v2.ReadEntryGRPCResponse.Payload
	1,  // 4: messages.notebook.v2.StartNewEntryGRPCRequest.principal:type_name -> messages.notebook.v2.Principal
	8,  // 5: messages.notebook.v2.StartNewEntryGRPCRequest.payload:type_name -> messages.notebook.v2.StartNewEntryGRPCRequest.Payload
	9,  // 6: messages.notebook.v2.StartNewEntryGRPCResponse.payload:type_name -> messages.notebook.v2.StartNewEntryGRPCResponse.Payload
	10, // 7: messages.notebook.v2.ReadEntryGRPCResponse.Payload.created_at:type_name -> google.protobuf.Timestamp
	10, // 8: messages.notebook.v2.ReadEntryGRPCResponse.Payload.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 9: messages.notebook.v2.Notebook.ReadEntry:input_type -> messages.notebook.v2.ReadEntryGRPCRequest
	4,  // 10: messages.notebook.v2.Notebook.StartNewEntry:input_type -> messages.notebook.v2.StartNewEntryGRPCRequest
	3,  // 11: messages.notebook.v2.Notebook.ReadEntry:output_type -> messages.notebook.v2.ReadEntryGRPCResponse
	5,  // 12: messages.notebook.v2.Notebook.StartNewEntry:output_type -> messages.notebook.v2.StartNewEntryGRPCResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_notebook_v2_notebook_proto_init() }
func file_notebook_v2_notebook_proto_init() {
	if File_notebook_v2_notebook_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_notebook_v2_notebook_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Principal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notebook_v2_notebook_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadEntryGRPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notebook_v2_notebook_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadEntryGRPCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notebook_v2_notebook_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartNewEntryGRPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notebook_v2_notebook_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartNewEntryGRPCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notebook_v2_notebook_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadEntryGRPCRequest_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notebook_v2_notebook_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadEntryGRPCResponse_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notebook_v2_notebook_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartNewEntryGRPCRequest_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_notebook_v2_notebook_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartNewEntryGRPCResponse_Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_notebook_v2_notebook_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notebook_v2_notebook_proto_goTypes,
		DependencyIndexes: file_notebook_v2_notebook_proto_depIdxs,
		EnumInfos:         file_notebook_v2_notebook_proto_enumTypes,
		MessageInfos:      file_notebook_v2_notebook_proto_msgTypes,
	}.Build()
	File_notebook_v2_notebook_proto = out.File
	file_notebook_v2_notebook_proto_rawDesc = nil
	file_notebook_v2_notebook_proto_goTypes = nil
	file_notebook_v2_notebook_proto_depIdxs = nil
}
